fix ant build failure on multiple call to resolve target
Failed build:
https://github.com/yacy/yacy_search_server/runs/6859314856

Relevant build log:

resolve:
[ivy:retrieve] ivy.instance reference an ivy:settings defined in an other classloader.  An new default one will be used in this project.
[ivy:retrieve] :: Apache Ivy non official version -  :: http://ant.apache.org/ivy/ ::
[ivy:retrieve] :: loading settings :: url = jar:file:/usr/share/java/ivy.jar!/org/apache/ivy/core/settings/ivysettings.xml
BUILD FAILED
/home/yacy/actions-runner/_work/yacy_search_server/yacy_search_server/build.xml:111:
 java.lang.ClassCastException: org.apache.ivy.core.module.descriptor.DefaultModuleDescriptor
 cannot be cast to org.apache.ivy.core.module.descriptor.ModuleDescriptor

Finding:

The second call to the resolve target in ant failed apparently due to
two instances of Ivy in the java runtime.
Without full investigation, the problem could be fixed by ensuring that
the resolve target is only called once within one ant build.