Fix build error for IntelliJ after fake sourceSet htroot has been add ( https://github.com/yacy/yacy_search_server/pull/443/commits/dfc7a23e603eb2bf2466d4ae69553e530191b1df )
commit https://github.com/yacy/yacy_search_server/pull/443/commits/dfc7a23e603eb2bf2466d4ae69553e530191b1df  uncomments the fake additional Gradle sourceSet (to make htroot in IDE visible), resulting in build error in IntelliJ IDEA if one uses just the IDE build button (and the old Ant build.xml is not available ... what is to expect soon).
This button runs as to expect the default Gradle task
   > Task :htrootClasses    (not our task compileHtrootServlets)
result :
htroot\processing\domaingraph\applet\domaingraph.java:1: error: package processing.core does not exist
import processing.core.*; import traer.physics.*; import traer.animation.*; import processing.net.*; import java.applet.*; import java.awt.*; import java.awt.image.*; import java.awt.event.*; import java.io.*; import java.net.*; import java.text.*; import java.util.*; import java.util.zip.*; public class domaingraph extends PApplet {// Domain visualization graph for YaCy